src/entity/Cross.java
package entity;

import database.Database;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Dictionary;

public class Cross implements IDbEntity {
    private Integer id = 0;
    private String name;
    private String description;
    private Integer nrOfRatings = 0;
    private Float averageRating = 0f;
    private String imageName;
    private Double latitude;
    private Double longitude;
    private Date createdOn;

    @Override
    public void loadData(ResultSet resultSet) throws SQLException {
        this.createdOn = resultSet.getDate("created_on");
        this.name = resultSet.getString("name");
        this.description = resultSet.getString("description");
        this.nrOfRatings = resultSet.getInt("nr_of_ratings");
        this.averageRating = resultSet.getFloat("average_rating");
        this.imageName = resultSet.getString("image_name");
        this.latitude = resultSet.getDouble("latitude");
        this.longitude = resultSet.getDouble("longitude");
    }

    public void saveData(Dictionary<String,String> data) {
        if (this.createdOn == null || this.createdOn.before(new Date(1971, 1, 1))) {
            this.createdOn = new Date();
        }

        data.put("created_on", (new SimpleDateFormat("yyyy-MM-dd hh:mm:ss")).format(this.createdOn));
        data.put("name", this.name);
        data.put("description", this.description);
        data.put("nr_of_ratings", this.nrOfRatings.toString());
        data.put("average_rating", this.averageRating.toString());

        if (this.imageName != null) {
            data.put("image_name", this.imageName);
        }

        data.put("latitude", this.latitude.toString());
        data.put("longitude", this.longitude.toString());
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getNrOfRatings() {
        return nrOfRatings;
    }

    public void setNrOfRatings(Integer nrOfRatings) {
        this.nrOfRatings = nrOfRatings;
    }

    public Float getAverageRating() {
        return averageRating;
    }

    public void setAverageRating(Float averageRating) {
        this.averageRating = averageRating;
    }

    public String getImageName() {
        return imageName;
    }

    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public void updateStatistics() {
        Database db = new Database();
        Statement statement = db.createStatement();

        try {
            ResultSet result = statement.executeQuery("SELECT count(*) as number, SUM(rating) as summary FROM ratings WHERE cross_id=" + this.id);
            result.next();

            this.nrOfRatings = result.getInt("number");
            this.averageRating = result.getFloat("summary") / this.nrOfRatings;

            result.close();
            statement.close();
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    public String getCreatedOnFormatted() {
        return (new SimpleDateFormat("dd.MM.yyyy")).format(this.createdOn);
    }

}

src/entity/Rating.java
package entity;

import database.Database;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Dictionary;

public class Rating implements IDbEntity {
    Integer id = 0;
    Integer userId;
    Date createdOn;
    String text;
    Integer rating;
    Integer crossId;

    @Override
    public void loadData(ResultSet resultSet) throws SQLException {
        this.id = resultSet.getInt("id");
        this.userId = resultSet.getInt("user_id");
        this.createdOn = resultSet.getDate("created_on");
        this.text = resultSet.getString("text");
        this.rating = resultSet.getInt("rating");
        this.crossId = resultSet.getInt("cross_id");
    }

    @Override
    public void saveData(Dictionary<String, String> data) {
        data.put("user_id", this.userId.toString());
        data.put("created_on", (new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(this.createdOn));
        data.put("text", this.text);
        data.put("rating", this.rating.toString());
        data.put("cross_id", this.crossId.toString());
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        Database db = new Database();
        User user = db.readOneEntity(User.class, "id=" + this.getUserId());
        return user.userName;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getCreatedOnFormatted() {
        return (new SimpleDateFormat("dd.MM.yyyy")).format(this.createdOn);
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getRating() {
        return rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    public Integer getCrossId() {
        return crossId;
    }

    public void setCrossId(Integer crossId) {
        this.crossId = crossId;
    }

    public String getCrossName() {
        Database db = new Database();
        Cross cross = db.readOneEntity(Cross.class, "id=" + this.crossId);
        return cross.getName();
    }
}

src/servlets/DetailServlet.java
package servlets;

import database.Database;
import entity.Cross;
import entity.Rating;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.util.Date;

@WebServlet("/detail")
public class DetailServlet extends ServletBase {
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        Database db = new Database();

        Cross cross = db.readOneEntity(Cross.class, "id=" + Integer.parseInt(request.getParameter("id")));
        Rating[] ratings = db.readEntities(Rating.class,"cross_id=" + cross.getId(), "created_on DESC");
        Rating myRating = loadMyRating(db, cross.getId(), getUserId(request.getSession()));

        request.setAttribute("cross", cross);
        request.setAttribute("ratings", ratings);
        request.setAttribute("hasRatings", ratings.length > 0);
        request.setAttribute("myRating", myRating);

        this.showView(request, response, "detail", cross.getName());
    }

    private Rating loadMyRating(Database db, Integer crossId, int userId) {
        return db.readOneEntity(Rating.class, "cross_id=" + crossId + " AND user_id=" + userId);
    }

    private int getUserId(HttpSession session) {
        Object rawUserId = session.getAttribute("user_id");
        return rawUserId != null ? (int)rawUserId : 0;
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");

        Database db = new Database();
        int crossId = Integer.parseInt(request.getParameter("id"));
        int userId = getUserId(request.getSession());

        Rating myRating = loadMyRating(db, crossId, userId);
        boolean isNewRating = myRating.getId() == 0;

        if (isNewRating) {
            myRating.setUserId(userId);
        }

        myRating.setCreatedOn(new Date());
        myRating.setCrossId(crossId);
        myRating.setRating(Integer.parseInt(request.getParameter("rating")));
        myRating.setText(request.getParameter("text"));
        db.save(myRating);

        // Update cross statistics
        Cross cross = db.readOneEntity(Cross.class, "id=" + Integer.parseInt(request.getParameter("id")));
        cross.updateStatistics();
        db.save(cross);

        this.doGet(request, response);
    }
}

src/servlets/EditServlet.java
package servlets;

import database.Database;
import entity.Cross;
import entity.Rating;
import entity.User;

import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Part;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;

@WebServlet("/edit")
@MultipartConfig
public class EditServlet extends ServletBase {
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        Cross cross = loadCross(request);

        if (!checkPermission(request, response, cross)) {
            return;
        }

        request.setAttribute("cross", cross);

        this.showView(request, response, "edit", cross.getId() == 0 ? "Neue Kreuzung erstellen" : "\"" + cross.getName() + "\" bearbeiten");
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");
        Cross cross = loadCross(request);

        if (!checkPermission(request, response, cross)) {
            return;
        }

        cross.setName(request.getParameter("name"));
        cross.setDescription(request.getParameter("description"));
        cross.setLatitude(Double.parseDouble(request.getParameter("lat")));
        cross.setLongitude(Double.parseDouble(request.getParameter("lng")));

        // Upload file
        this.handleFileUpload(request, cross);

        Database database = new Database();
        database.save(cross);

        response.sendRedirect("detail?id=" + cross.getId());
    }

    private void handleFileUpload(HttpServletRequest request, Cross cross) throws IOException, ServletException {
        Random random = new Random();
        Part image = request.getPart("image");

        if (image.getSize() == 0) {
            return;
        }

        String filename = random.nextInt(9999999) + "-" + image.getSubmittedFileName();
        String fullFilename = this.getServletContext().getRealPath("images/crosses/" + filename);

        image.write(fullFilename);
        cross.setImageName(filename);
    }

    private Cross loadCross(HttpServletRequest request) {
        Cross cross = new Cross();
        String idParameter = request.getParameter("id");

        if (idParameter != null) {
            Database db = new Database();

            cross = db.readOneEntity(Cross.class, "id=" + Integer.parseInt(idParameter));
        }

        return cross;
    }

    private boolean checkPermission(HttpServletRequest request, HttpServletResponse response, Cross cross) throws IOException {
        User user = this.getCurrentUser(request);
        if (user.getId() == 0) {
            response.sendRedirect("/"); // Not logged in
            return false;
        }

        if (cross.getId() > 0 && !user.getAdministrator()) {
            response.sendRedirect("/edit"); // Not a administrator, is only allowed to create new crosses
            return false;
        }

        return true;
    }
}

src/servlets/HomeServlet.java
package servlets;

import database.Database;
import entity.Cross;
import entity.IDbEntity;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.ArrayList;

@WebServlet("")
public class HomeServlet extends ServletBase {
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        Database db = new Database();

        Cross[] newCrosses = db.readEntities(Cross.class,"1=1", "created_on DESC");
        Cross[] popularCrosses = db.readEntities(Cross.class,"1=1", "nr_of_ratings DESC");
        Cross[] mapCrosses = db.readEntities(Cross.class, "1=1", "id");

        request.setAttribute("newCrosses", newCrosses);
        request.setAttribute("popularCrosses", popularCrosses);
        request.setAttribute("mapCrosses", mapCrosses);

        this.showView(request, response, "home", "Bewerte Kreuzungen um sie besser zu machen");
    }
}

src/servlets/LoginServlet.java
package servlets;

import database.Database;
import entity.User;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;

@WebServlet("/login")
public class LoginServlet extends ServletBase {
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        this.showView(request, response, "login", "Anmeldung");
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String action = request.getParameter("action");
        boolean success = false;

        switch (action) {
            case "login":
                success = login(request);
                break;
            case "register":
                success = register(request);
                break;
        }

        if (success) {
            response.sendRedirect("/");
        } else {
            this.doGet(request, response);
        }
    }

    private boolean login(HttpServletRequest request) {
        User user = loadUserByEmail(request.getParameter("email"));
        if (!user.comparePlainPassword(request.getParameter("password"))) {
            request.setAttribute("login_error", "Die Kombination aus E-Mail Adresse und Passwort ist falsch");
            return false;
        }

        // Login
        doLogin(user, request.getSession());
        return true;
    }

    private boolean register(HttpServletRequest request) {
        String password1 = request.getParameter("password1");
        String password2 = request.getParameter("password2");

        if (password1 == null || !password1.equals(password2)) {
            request.setAttribute("register_error", "Die Passwörter stimmen nicht überein");
            return false;
        }

        String email = request.getParameter("email");
        User user = loadUserByEmail(email);

        if (user.getId() > 0) {
            request.setAttribute("register_error", "Es existiert bereits ein Benutzer mit dieser E-Mail Adresse");
            return false;
        }

        user.setUserName(request.getParameter("username"));
        user.setEmail(email);
        user.setPassword(user.encodePassword(password1));
        user.setAdministrator(false);

        Database db = new Database();
        boolean success = db.save(user);

        if (success) {
            doLogin(user, request.getSession());
        }

        return success;
    }

    private void doLogin(User user, HttpSession session) {
        session.setAttribute("user_id", user.getId());
    }

    private User loadUserByEmail(String email) {
        Database db = new Database();
        return db.readOneEntity(User.class, "email='" + email.replace("'", "''") + "'");
    }
}

web/content/detail.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<h1 class="my-3 text-center">${fn:escapeXml(cross.name)}</h1>
<c:if test="${user_isAdministrator}">
    <p class="text-center">
        <a href="/edit?id=${cross.id}">Kreuzung bearbeiten</a>
    </p>
</c:if>
<p class="text-center">
    <span class="rating">
        <jsp:include page="../includes/rating.jsp">
            <jsp:param name="rating" value="${cross.averageRating}"/>
        </jsp:include>
    </span>
    ${cross.nrOfRatings} Bewertungen
</p>
<div class="row bg-light p-3 mb-3">
    <div class="col-md">
        <p class="pre">${fn:escapeXml(cross.description)}</p>
        <p>
            <img src="/images/crosses/${cross.imageName}" style="width: 100%">
        </p>
        <div id="map"></div>
    </div>
    <div class="col-md">
        <h2>Bewertungen</h2>
        <c:forEach items="${ratings}" var="rating">
            <p>
                <span class="rating">
                    <jsp:include page="../includes/rating.jsp">
                        <jsp:param name="rating" value="${rating.rating}" />
                    </jsp:include>
                </span>
                <strong>${fn:escapeXml(rating.userName)}</strong> am ${rating.createdOnFormatted}:<br>
                <div class="pre">${fn:escapeXml(rating.text)}</div>
            </p>
        </c:forEach>

        <c:if test="${!hasRatings}">
            <p>Bisher wurden keine Bewertungen verfasst.</p>
        </c:if>

        <h2 class="mt-5 mb-3">Eigene Bewertung verfassen</h2>
        <c:if test="${user_isLoggedIn}">
            <form method="post">
                <div class="form-group">
                    <label for="rating">Ihre Bewertung:</label>
                    <select class="form-control" id="rating" name="rating">
                        <option>Bitte wählen…</option>
                        <option value="1" <c:if test="${myRating.rating == 1}">selected</c:if>>1 Stern</option>
                        <option value="2" <c:if test="${myRating.rating == 2}">selected</c:if>>2 Sterne</option>
                        <option value="3" <c:if test="${myRating.rating == 3}">selected</c:if>>3 Sterne</option>
                        <option value="4" <c:if test="${myRating.rating == 4}">selected</c:if>>4 Sterne</option>
                        <option value="5" <c:if test="${myRating.rating == 5}">selected</c:if>>5 Sterne</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="text">Ihre Rezension:</label>
                    <textarea class="form-control" style="min-height: 150px;" id="text" name="text">${myRating.text}</textarea>
                </div>

                <div class="form-group">
                    <button class="btn btn-primary">Bewertung <c:if test="${myRating.id == 0}">veröffentlichen</c:if><c:if test="${myRating.id > 0}">ändern</c:if></button>
                </div>
            </form>
        </c:if>
        <c:if test="${!user_isLoggedIn}">
            <p><a href="/login">Bitte melden Sie sich an, um eine Bewertung zu verfassen.</a></p>
        </c:if>
    </div>
</div>

<script>
      function initMap() {
        var myLatLng = {lat: ${cross.latitude}, lng: ${cross.longitude}};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: '${cross.name}'
        });
      }
    </script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA78HUHnY54dlv3YqzJeTA4SQYDsCkSrz4&callback=initMap">
</script>

web/content/edit.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c" %>

<h1 class="my-3 text-center"><c:if test="${cross.id == 0}">Neue Kreuzung anlegen</c:if><c:if test="${cross.id > 0}">"${cross.name}" bearbeiten</c:if></h1>
<form method="post" enctype="multipart/form-data">
    <div class="row bg-light p-3 mb-3">
        <div class="col-md">
            <div class="form-group">
                <label for="name">Name</label>
                <input class="form-control" type="text" id="name" name="name" value="${cross.name}">
            </div>
            <div class="form-group">
                <label for="description">Beschreibung</label>
                <textarea class="form-control" style="min-height: 300px;" id="description" name="description">${cross.description}</textarea>
            </div>
            <c:if test="${cross.id > 0}">
            <div class="form-group">
                <img src="/images/crosses/${cross.imageName}" style="width: 100%">
            </div>
            </c:if>
            <div class="form-group">
                <label for="image">Bild hochladen</label>
                <div><input id="image" name="image" type="file"></div>
            </div>

        </div>
        <div class="col-md">
            <div class="form-group">
                <label>Position wählen</label>
                <div id="map"></div>
                <input id="lat" type="hidden" name="lat">
                <input id="lng" type="hidden" name="lng">
            </div>
        </div>
    </div>
    <div class="form-group text-center">
        <c:if test="${cross.id > 0}">
            <button class="btn btn-link">Zurück</button>
        </c:if>
        <button class="btn btn-primary" type="submit">Speichern</button>
    </div>
</form>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA78HUHnY54dlv3YqzJeTA4SQYDsCkSrz4"></script>
<script src="/lib/location-picker.min.js"></script>

<script>
  var lp = new locationPicker('map', {
    <c:if test="${cross.id > 0}">
        lat: ${cross.latitude},
        lng: ${cross.longitude}
    </c:if>
    <c:if test="${cross.id == 0}">
        lat: 48.210033, // Use vienna as default when no location is available
        lng: 16.363449,
        setCurrentPosition: true
    </c:if>
  });

  var latHidden = document.getElementById('lat');
  var lngHidden = document.getElementById('lng');

  // Set changes to hidden field
  google.maps.event.addListener(lp.map, 'idle', function (event) {
    var location = lp.getMarkerPosition();

    latHidden.value = location.lat;
    lngHidden.value = location.lng;
  });
</script>

web/content/home.jsp
<%@ page import="entity.Cross" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix = "c" uri = "http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/functions" prefix = "fn" %>
<%--<div class="jumbotron my-3">
    <form>
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Nach Kreuzungen suchen">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="button-addon2" onclick="document.location.href='/detail?id=1';">Suchen</button>
            </div>
        </div>
    </form>
</div>--%>

<div class="mb-3">
    <div id="map"></div>
</div>

<div class="row mb-3">
    <div class="col-md">
        <table class="table">
            <colgroup>
                <col width="100px">
            </colgroup>
            <thead class="thead-light">
            <tr>
                <th scope="col" colspan="2">Neueste Kreuzungen</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${newCrosses}" var="cross">
            <tr>
                <th scope="row">${cross.createdOnFormatted}</th>
                <td><a href="/detail?id=${cross.id}">${cross.name}</a></td>
            </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>

    <div class="col-md">
        <table class="table">
            <colgroup>
                <col width="170px">
            </colgroup>
            <thead class="thead-light">
            <tr>
                <th scope="col" colspan="2">Kreuzungen über die gesprochen wird</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${popularCrosses}" var="cross">
                <tr>
                    <th scope="row">${cross.nrOfRatings} Bewertungen</th>
                    <td><a href="/detail?id=${cross.id}">${cross.name}</a></td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>
</div>


<script>
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 7,
            center: {
                lat: 47.607798,
                lng: 13.300144
            }
        });

        var infowindow = new google.maps.InfoWindow();

        // Geolocation
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                map.setCenter(pos);
                map.setZoom(9);
            }, function() {
                console.error('geolocation error');
            });
        }

        <c:forEach items="${newCrosses}" var="cross">
        var marker${cross.id} = new google.maps.Marker({
            position: {
                lat: ${cross.latitude},
                lng: ${cross.longitude}
            },
            map: map,
            title: '${cross.name}'
        });

        marker${cross.id}.addListener('click', function() {
            infowindow.open(map, marker${cross.id});
            infowindow.setContent('<a href="/detail?id=${cross.id}">${fn:replace(cross.name,"'", "\\'")}</a>');
        });
        </c:forEach>
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA78HUHnY54dlv3YqzJeTA4SQYDsCkSrz4&callback=initMap">
</script>

web/content/profile.jsp
<%--
  Created by IntelliJ IDEA.
  User: herbert
  Date: 04.12.18
  Time: 21:30
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c" %>
<h1 class="my-4 text-center">Mein Benutzerprofil</h1>
<div class="row">
    <div class="col-md text-truncate">
        <div class="bg-light p-4 mb-3">
            <h2>Meine Bewertungen</h2>
            <c:forEach items="${ratings}" var="rating">
                <a href="/detail?id=${rating.crossId}">${rating.crossName}</a>
                <div class="text-truncate">
                    <small>${rating.text}</small>
                </div>
                <hr>
            </c:forEach>
        </div>
    </div>
    <div class="col-md">
        <form class="bg-light p-4 mb-3" method="post">
            <input type="hidden" name="action" value="change_username">
            <h2>Meine Daten</h2>
            <div class="form-group">
                <label for="email">Ihre E-Mail Adresse</label>
                <input class="form-control" id="email" disabled value="${currentUser.email}">
            </div>
            <div class="form-group">
                <label for="username">Öffentlicher Benutzername</label>
                <input class="form-control" id="username" name="username" value="${currentUser.userName}" required>
            </div>
            <c:if test="${username_error != null}">
                <p class="text-danger">${username_error}</p>
            </c:if>
            <c:if test="${username_success != null}">
                <p class="text-success">${username_success}</p>
            </c:if>
            <button class="btn btn-primary">Daten speichern</button>
        </form>

        <form class="bg-light p-4 mb-3" method="post">
            <input type="hidden" name="action" value="change_password">
            <h2>Passwort ändern</h2>
            <div class="form-group">
                <label for="password_old">Altes Passwort</label>
                <input id="password_old" name="password_old" class="form-control" type="password" required>
            </div>
            <div class="form-group">
                <label for="password_new1">Neues Passwort</label>
                <input id="password_new1" name="password_new1" class="form-control" type="password" required>
            </div>
            <div class="form-group">
                <label for="password_new2">Neues Passwort wiederholen</label>
                <input id="password_new2" name="password_new2" class="form-control" type="password" required>
            </div>
            <c:if test="${password_error != null}">
                <p class="text-danger">${password_error}</p>
            </c:if>
            <c:if test="${password_success != null}">
                <p class="text-success">${password_success}</p>
            </c:if>
            <button class="btn btn-primary">Passwort ändern</button>
        </form>
    </div>
</div>